<?php
define('MESSAGE_TYPE_SERVICE', 1);
define('MESSAGE_TYPE_NOTIFICATION', 2);
define('MESSAGE_TYPE_CAMPAIGN', 3);
define('SMS_SIGN_SHENFENRENZHENG', '身份验证');
define('SMS_SIGN_SHENFENRENZHENG_TEMPLATE_ID', 'SMS_61165002');
define('SMS_SENDING_LIMIT_NUMBERS', 200);

module_load_include('inc', 'users', 'includes/sms');

/**
 * Implementation of hook_services_resources()
 * @return array
 */
function juna_private_message_services_resources() {
  return array(
    'mymessage' => array(
      'operations' => array(
        'index' => array(
          'help' => t('获取我的私信'),
          'callback' => 'juna_private_message_my_message',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'page',
              'optional' => TRUE,
              'source' => array('param' => 'page'),
              'description' => t('页码'),
              'type' => 'int',
              'default value' => 1,
            ),
          ),
          'file' => array(
            'type' => 'inc',
            'module' => 'juna_private_message',
            'name' => 'includes/juna_private_message.resource'
          ),
        ),
      ),
      'actions' => array(
        'update' => array(
          'help' => t('私信设置为已读'),
          'callback' => 'juna_private_message_setread_message',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'mid',
              'optional' => FALSE,
              'source' => array('data' => 'mid'),
              'description' => t('私信thread id'),
              'type' => 'int',
            ),
          ),
          'file' => array(
            'type' => 'inc',
            'module' => 'juna_private_message',
            'name' => 'includes/juna_private_message.resource'
          ),
        )
      ),
    ),
  );
}

/**
 * Implementation of hook_privatemsg_message_insert().
 * @param $message
 */
function juna_private_message_privatemsg_message_insert($message) {
  $status = '未通过';
  if ($message->field_message_type[LANGUAGE_NONE][0]['value'] == 1) {
    $phone_numbers = array();
    if ($message->field_passed[LANGUAGE_NONE][0]['value'] == 1) {
      $status = '已通过';
    }
    foreach ($message->recipients as $key => $recipient) {
      $phone_numbers[] = $recipient->name;
    }
    smsSending(implode(',', $phone_numbers), SMS_SIGN_SHENFENRENZHENG, array('status' => $status), SMS_SIGN_SHENFENRENZHENG_TEMPLATE_ID);
  }
}
