<?php
define('MESSAGE_TYPE_SERVICE', 1);
define('MESSAGE_TYPE_NOTIFICATION', 2);
define('MESSAGE_TYPE_CAMPAIGN', 3);

/**
 * Implementation of hook_services_resources()
 * @return array
 */
function juna_private_message_services_resources() {
  return array(
    'mymessage' => array(
      'operations' => array(
        'index' => array(
          'help' => t('获取我的私信'),
          'callback' => 'juna_private_message_my_message',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'page',
              'optional' => TRUE,
              'source' => array('param' => 'page'),
              'description' => t('页码'),
              'type' => 'int',
              'default value' => 1,
            ),
          ),
          'file' => array(
            'type' => 'inc',
            'module' => 'juna_private_message',
            'name' => 'includes/juna_private_message.resource'
          ),
        ),
      ),
      'actions' => array(
        'update' => array(
          'help' => t('私信设置为已读'),
          'callback' => 'juna_private_message_setread_message',
          'access arguments' => array('access content'),
          'args' => array(
            array(
              'name' => 'mid',
              'optional' => FALSE,
              'source' => array('data' => 'mid'),
              'description' => t('私信thread id'),
              'type' => 'int',
            ),
          ),
          'file' => array(
            'type' => 'inc',
            'module' => 'juna_private_message',
            'name' => 'includes/juna_private_message.resource'
          ),
        )
      ),
    ),
  );
}
