<?php

/**
 * Implementation of hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function junashare_service_theme($existing, $type, $theme, $path) {
  return array(
    'sku_product_detail_wrapper' => array(
      'variables' => array(
        'content' => '',
      ),
    )
  );
}

/**
 * Implementation of theme sku_product_detail_wrapper.
 * @param $content
 * @return string
 */
function theme_sku_product_detail_wrapper($content) {
  return '<div id="sku-content">' . $content . '</div>';
}
